### ISSUE TITLE
adding weapon animations

### ISSUE THREAD

**Issue by DozorXGameDev** [yuzukianzu/InventorySystem#1]
I have a question is it possible to add animations of weapons, weapon mechanics, shooting or stabbing, if possible, tell me how I am still new to this business

**Comment by shulgastanslv** [comment]
Of course you can! You need to write an event that happens after dragging something into the slot. After that, just play the animation + spawn in the hand of the weapon. When you remove the weapon + event from the slot.

**Comment by DozorXGameDev** [comment]
thanks)

**Comment by DozorXGameDev** [comment]
Will there be any more updates or is that all?

**Comment by DozorXGameDev** [comment]
And why a stalker? and isn't this related to the fact that a sequel is coming out soon?

**Comment by shulgastanslv** [comment]
> And why a stalker? and isn't this related to the fact that a sequel is coming out soon?

No. Just the my pet-project.

**Comment by shulgastanslv** [comment]
> Will there be any more updates or is that all?

At this moment - Just All :)
